import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '../src/components/Header';
import Providers from './providers';
import { ToastContainer } from 'react-toastify';
import * as Sentry from "@sentry/nextjs";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    ...Sentry.getTraceData(),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <Providers>
          <Header />
          <main className="flex flex-1 mx-auto w-full max-w-7xl px-4 py-6">
            {children}
          </main>
          {/* Footer */}
          <footer className="py-8 text-center text-sm text-gray-500">
            © {new Date().getFullYear()} Invoice-PDF. All rights reserved.
          </footer>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
